name: riverpod_drift_example
description: "Demonstrates how to use the riverpod_drift plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  riverpod_drift:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  drift_dev: ^2.28.2

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
